import { PrismaClient } from '@prisma/client'
import bcryptjs from 'bcryptjs'

const prisma = new PrismaClient()

const dishes = [
  // BREAKFAST
  {
    name: "Power Paneer Paratha",
    description: "Whole wheat paratha stuffed with cottage cheese, paneer, and Indian spices. Lab-tested macros for muscle building.",
    category: "BREAKFAST",
    tags: ["High Protein", "Lacto Vegetarian"],
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500",
    priceSmall: 199,
    priceMedium: 249,
    priceLarge: 299,
    calories: 485,
    protein: 22,
    carbs: 58,
    carbsFiber: 7,
    fat: 14,
    fatSaturated: 4,
    vitaminD: 2.5,
    calcium: 150,
    iron: 3.2,
    allergens: ["gluten", "dairy"],
    isJain: false,
    isFasting: false,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 1,
  },
  {
    name: "Protein Oat Bowl",
    description: "Steel-cut oats with protein powder, berries, nuts, and honey. Perfect for muscle building breakfast.",
    category: "BREAKFAST",
    tags: ["High Protein", "Vegan Option"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500",
    priceSmall: 179,
    priceMedium: 229,
    priceLarge: 279,
    calories: 420,
    protein: 28,
    carbs: 52,
    carbsFiber: 8,
    fat: 10,
    fatSaturated: 2,
    vitaminD: 3,
    calcium: 200,
    iron: 4.1,
    allergens: ["gluten", "nuts"],
    isJain: false,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 2,
  },
  {
    name: "Saatvik Idli Sambar",
    description: "Soft steamed rice and lentil idlis with aromatic sambar. Pure vegetarian, Jain-friendly.",
    category: "BREAKFAST",
    tags: ["Jain Friendly", "Low Fat"],
    imageUrl: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=500",
    priceSmall: 149,
    priceMedium: 189,
    priceLarge: 239,
    calories: 320,
    protein: 12,
    carbs: 62,
    carbsFiber: 3,
    fat: 2,
    fatSaturated: 0.5,
    vitaminD: 1,
    calcium: 80,
    iron: 2.1,
    allergens: [],
    isJain: true,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 3,
  },
  {
    name: "Paneer Tikka Omelette",
    description: "Fluffy 4-egg omelette with grilled paneer tikka, peppers, and onions. High protein breakfast champion.",
    category: "BREAKFAST",
    tags: ["High Protein", "Keto Friendly"],
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500",
    priceSmall: 249,
    priceMedium: 299,
    priceLarge: 349,
    calories: 520,
    protein: 42,
    carbs: 8,
    carbsFiber: 2,
    fat: 36,
    fatSaturated: 15,
    vitaminD: 5,
    calcium: 220,
    iron: 3.5,
    allergens: ["dairy"],
    isJain: false,
    isFasting: false,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 4,
  },

  // LUNCH
  {
    name: "Dal Makhani with Basmati Rice",
    description: "Creamy black lentils and kidney beans in a rich tomato-based sauce. Perfectly balanced macros.",
    category: "LUNCH",
    tags: ["Comfort Food", "Protein Rich"],
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500",
    priceSmall: 229,
    priceMedium: 279,
    priceLarge: 329,
    calories: 580,
    protein: 24,
    carbs: 72,
    carbsFiber: 8,
    fat: 16,
    fatSaturated: 5,
    vitaminD: 2,
    calcium: 160,
    iron: 5.2,
    allergens: ["dairy"],
    isJain: false,
    isFasting: false,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 5,
  },
  {
    name: "Chole Bhature",
    description: "Fluffy fried bread with spiced chickpea curry. Traditional Indian comfort meal.",
    category: "LUNCH",
    tags: ["Comfort Food", "Vegetarian"],
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500",
    priceSmall: 199,
    priceMedium: 249,
    priceLarge: 299,
    calories: 620,
    protein: 18,
    carbs: 88,
    carbsFiber: 10,
    fat: 18,
    fatSaturated: 3,
    vitaminD: 1,
    calcium: 140,
    iron: 6.1,
    allergens: ["gluten"],
    isJain: false,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 6,
  },
  {
    name: "Paneer Tikka Masala with Brown Rice",
    description: "Grilled paneer in creamy tomato sauce with brown rice. High protein lunch option.",
    category: "LUNCH",
    tags: ["High Protein", "Restaurant Quality"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    priceSmall: 299,
    priceMedium: 349,
    priceLarge: 399,
    calories: 580,
    protein: 38,
    carbs: 58,
    carbsFiber: 6,
    fat: 20,
    fatSaturated: 8,
    vitaminD: 3,
    calcium: 280,
    iron: 3.8,
    allergens: ["dairy"],
    isJain: false,
    isFasting: false,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 7,
  },
  {
    name: "Mixed Vegetable Pulao",
    description: "Fragrant basmati rice with seasonal vegetables and light spices. Jain-friendly.",
    category: "LUNCH",
    tags: ["Jain Friendly", "Low Oil"],
    imageUrl: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=500",
    priceSmall: 179,
    priceMedium: 229,
    priceLarge: 279,
    calories: 420,
    protein: 10,
    carbs: 78,
    carbsFiber: 7,
    fat: 6,
    fatSaturated: 1,
    vitaminD: 1.5,
    calcium: 100,
    iron: 2.9,
    allergens: [],
    isJain: true,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 8,
  },

  // DINNER
  {
    name: "Grilled Paneer Steaks with Salad",
    description: "Thick-cut marinated paneer steaks grilled to perfection with fresh greens. High protein, low carb.",
    category: "DINNER",
    tags: ["High Protein", "Low Carb", "Keto Friendly"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    priceSmall: 299,
    priceMedium: 349,
    priceLarge: 399,
    calories: 380,
    protein: 48,
    carbs: 12,
    carbsFiber: 4,
    fat: 18,
    fatSaturated: 7,
    vitaminD: 4,
    calcium: 320,
    iron: 2.5,
    allergens: ["dairy"],
    isJain: false,
    isFasting: false,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 9,
  },
  {
    name: "Tofu Stir Fry with Quinoa",
    description: "Silken tofu with colorful vegetables and superfoods. Perfect vegan high-protein dinner.",
    category: "DINNER",
    tags: ["Vegan", "High Protein", "Superfood"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500",
    priceSmall: 279,
    priceMedium: 329,
    priceLarge: 379,
    calories: 420,
    protein: 32,
    carbs: 48,
    carbsFiber: 8,
    fat: 12,
    fatSaturated: 2,
    vitaminD: 2,
    calcium: 180,
    iron: 4.2,
    allergens: ["soy", "gluten"],
    isJain: false,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 10,
  },
  {
    name: "Chana Masala with Roti",
    description: "Chickpea curry with aromatic spices and whole wheat rotis. Complete protein meal.",
    category: "DINNER",
    tags: ["High Protein", "Vegan", "Budget Friendly"],
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500",
    priceSmall: 159,
    priceMedium: 199,
    priceLarge: 249,
    calories: 480,
    protein: 22,
    carbs: 68,
    carbsFiber: 12,
    fat: 10,
    fatSaturated: 2,
    vitaminD: 1,
    calcium: 140,
    iron: 5.8,
    allergens: ["gluten"],
    isJain: false,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 11,
  },

  // PROTEIN DRINKS
  {
    name: "Whey Protein Shake - Chocolate",
    description: "30g pure whey protein with natural cocoa and almonds. Fast recovery post-workout.",
    category: "PROTEIN_DRINKS",
    tags: ["High Protein", "Post Workout"],
    imageUrl: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500",
    priceSmall: 99,
    priceMedium: 129,
    priceLarge: 159,
    calories: 180,
    protein: 30,
    carbs: 8,
    carbsFiber: 1,
    fat: 4,
    fatSaturated: 1,
    vitaminD: 2,
    calcium: 200,
    iron: 1.2,
    allergens: ["dairy", "nuts"],
    isJain: false,
    isFasting: false,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 12,
  },
  {
    name: "Vegan Protein Smoothie - Mango",
    description: "Plant-based protein blend with fresh mango and coconut milk. 25g protein, completely vegan.",
    category: "PROTEIN_DRINKS",
    tags: ["Vegan", "High Protein", "Tropical"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500",
    priceSmall: 129,
    priceMedium: 159,
    priceLarge: 189,
    calories: 220,
    protein: 25,
    carbs: 32,
    carbsFiber: 3,
    fat: 5,
    fatSaturated: 3,
    vitaminD: 2.5,
    calcium: 150,
    iron: 2.1,
    allergens: ["soy"],
    isJain: false,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 13,
  },

  // FASTING / VRAT
  {
    name: "Sabudana Khichdi",
    description: "Fasting-friendly tapioca pearls with peanuts and rock salt. Perfect for Navratri.",
    category: "FASTING",
    tags: ["Navratri", "Ekadashi", "Fasting"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    priceSmall: 149,
    priceMedium: 189,
    priceLarge: 229,
    calories: 380,
    protein: 10,
    carbs: 68,
    carbsFiber: 2,
    fat: 8,
    fatSaturated: 1,
    vitaminD: 0.5,
    calcium: 60,
    iron: 1.8,
    allergens: ["peanuts"],
    isJain: false,
    isFasting: true,
    isVegan: true,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 14,
  },
  {
    name: "Milk Shake with Dry Fruits",
    description: "Creamy milk shake with almonds, cashews, and jaggery. Navratri approved.",
    category: "FASTING",
    tags: ["Navratri", "Milk", "Energy Drink"],
    imageUrl: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500",
    priceSmall: 179,
    priceMedium: 219,
    priceLarge: 259,
    calories: 320,
    protein: 12,
    carbs: 42,
    carbsFiber: 2,
    fat: 12,
    fatSaturated: 5,
    vitaminD: 3,
    calcium: 280,
    iron: 1.5,
    allergens: ["dairy", "nuts"],
    isJain: false,
    isFasting: true,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 15,
  },
  {
    name: "Makhane Kheer",
    description: "Fasting pudding with fox nuts, milk, and cardamom. Jain-friendly.",
    category: "FASTING",
    tags: ["Jain Friendly", "Ekadashi", "Dessert"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500",
    priceSmall: 169,
    priceMedium: 209,
    priceLarge: 249,
    calories: 280,
    protein: 8,
    carbs: 38,
    carbsFiber: 1,
    fat: 10,
    fatSaturated: 4,
    vitaminD: 2.5,
    calcium: 240,
    iron: 1.2,
    allergens: ["dairy"],
    isJain: true,
    isFasting: true,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 16,
  },

  // SNACKS
  {
    name: "Roasted Chickpea Snack Mix",
    description: "Crunchy spiced chickpeas with peanuts and seeds. High protein snack.",
    category: "SNACKS",
    tags: ["High Protein", "On-The-Go", "Vegan"],
    imageUrl: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64bed?w=500",
    priceSmall: 79,
    priceMedium: 99,
    priceLarge: 129,
    calories: 220,
    protein: 12,
    carbs: 24,
    carbsFiber: 6,
    fat: 8,
    fatSaturated: 1,
    vitaminD: 1,
    calcium: 100,
    iron: 3.2,
    allergens: ["peanuts"],
    isJain: false,
    isFasting: false,
    isVegan: true,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 17,
  },
  {
    name: "Cottage Cheese Balls",
    description: "Pan-fried paneer balls with herbs and spices. Keto-friendly snack.",
    category: "SNACKS",
    tags: ["High Protein", "Keto Friendly"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    priceSmall: 129,
    priceMedium: 159,
    priceLarge: 189,
    calories: 180,
    protein: 18,
    carbs: 6,
    carbsFiber: 1,
    fat: 10,
    fatSaturated: 5,
    vitaminD: 3,
    calcium: 220,
    iron: 1.8,
    allergens: ["dairy"],
    isJain: false,
    isFasting: false,
    isVegan: false,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 18,
  },
]

const promoCodes = [
  {
    code: "PUREVEG40",
    discountType: "PERCENT",
    discountValue: 40,
    maxUses: 500,
    expiresAt: new Date("2024-12-31"),
  },
  {
    code: "JAIN10",
    discountType: "PERCENT",
    discountValue: 10,
    maxUses: null,
    expiresAt: new Date("2024-12-31"),
  },
  {
    code: "NAVRATRI20",
    discountType: "PERCENT",
    discountValue: 20,
    maxUses: null,
    expiresAt: new Date("2024-10-31"),
  },
]

async function main() {
  console.log("🌱 Seeding database...")

  // Clear existing data
  await prisma.review.deleteMany()
  await prisma.cartItem.deleteMany()
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()
  await prisma.subscription.deleteMany()
  await prisma.aiProfile.deleteMany()
  await prisma.address.deleteMany()
  await prisma.user.deleteMany()
  await prisma.dish.deleteMany()
  await prisma.promoCode.deleteMany()

  console.log("✅ Cleared existing data")

  // Seed dishes
  for (const dish of dishes) {
    await prisma.dish.create({ data: dish })
  }
  console.log(`✅ Created ${dishes.length} dishes`)

  // Seed promo codes
  for (const promo of promoCodes) {
    await prisma.promoCode.create({ data: promo })
  }
  console.log(`✅ Created ${promoCodes.length} promo codes`)

  // Create admin user
  const adminPassword = await bcryptjs.hash("admin123", 10)
  const admin = await prisma.user.create({
    data: {
      name: "Admin User",
      email: "admin@purevegfitfuel.com",
      phone: "+919876543210",
      passwordHash: adminPassword,
      role: "ADMIN",
      isVerified: true,
    },
  })
  console.log("✅ Created admin user")

  // Create test customer
  const customerPassword = await bcryptjs.hash("customer123", 10)
  const customer = await prisma.user.create({
    data: {
      name: "John Fitness",
      email: "customer@example.com",
      phone: "+919123456789",
      passwordHash: customerPassword,
      role: "CUSTOMER",
      dietType: "LACTO_VEG",
      goal: "MUSCLE",
      isVerified: true,
      addresses: {
        create: {
          label: "Home",
          fullName: "John Fitness",
          phone: "+919123456789",
          email: "customer@example.com",
          street: "123 Fitness Road",
          sector: "Sector 29",
          city: "Gurgaon",
          state: "Haryana",
          zipCode: "122001",
          latitude: 28.4595,
          longitude: 77.0266,
          isDefault: true,
        },
      },
    },
    include: { addresses: true },
  })
  console.log("✅ Created test customer with address")

  // Create AI profile for customer
  await prisma.aiProfile.create({
    data: {
      userId: customer.id,
      goal: "MUSCLE",
      age: 28,
      weight: 75,
      height: 180,
      activityLevel: "moderate",
      budget: 800,
      allergies: [],
      tdee: 2500,
      macroProtein: 200,
      macroCarbs: 275,
      macroFat: 83,
    },
  })
  console.log("✅ Created AI profile for customer")

  console.log("✨ Database seeding completed!")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
